-- Insert users
insert into users (first_name, last_name, email, google_id, image) values ('Dannye', 'Rollings', 'drollings0@blogspot.com', 608261715242570195, 'http://dummyimage.com/191x100.png/dddddd/000000');
insert into users (first_name, last_name, email, google_id, image) values ('Seline', 'Faill', 'sfaill1@xrea.com', 969928527309815595, 'http://dummyimage.com/190x100.png/ff4444/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Dante', 'Egginson', 'degginson2@shop-pro.jp', 8866205792246198055, 'http://dummyimage.com/181x100.png/ff4444/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Deerdre', 'Lademann', 'dlademann3@irs.gov', 5907326693398798065, 'http://dummyimage.com/125x100.png/dddddd/000000');
insert into users (first_name, last_name, email, google_id, image) values ('Kylila', 'Petyt', 'kpetyt4@answers.com', 6929003285482273258, 'http://dummyimage.com/152x100.png/ff4444/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Lyn', 'Hatchard', 'lhatchard5@answers.com', 4813340279379411645, 'http://dummyimage.com/145x100.png/cc0000/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Ritchie', 'Iredell', 'riredell6@liveinternet.ru', 6973340838298613749, 'http://dummyimage.com/151x100.png/cc0000/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Nara', 'Lalor', 'nlalor7@goodreads.com', 1952566521327893590, 'http://dummyimage.com/222x100.png/cc0000/ffffff');
insert into users (first_name, last_name, email, google_id, image) values ('Roxine', 'Melloi', 'rmelloi8@twitter.com', 8765661569906649458, 'http://dummyimage.com/183x100.png/dddddd/000000');
insert into users (first_name, last_name, email, google_id, image) values ('Heall', 'Chantrell', 'hchantrell9@howstuffworks.com', 6754487065160906313, 'http://dummyimage.com/221x100.png/ff4444/ffffff');

-- Insert visibility options
INSERT INTO recipe_visibility (value) VALUES ('Public');
INSERT INTO recipe_visibility (value) VALUES ('Community');
INSERT INTO recipe_visibility (value) VALUES ('Private');
    
-- Insert recipes
insert into recipes (title, description, image, author_id, visibility_id) values ('in faucibus orci luctus et ultrices posuere cubilia', 'Suspendisse potenti.', 'http://dummyimage.com/123x134.png/5fa2dd/ffffff', 10, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('amet consectetuer adipiscing elit proin interdum', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'http://dummyimage.com/136x143.png/5fa2dd/ffffff', 7, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('luctus cum sociis', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', null, 10, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('augue quam sollicitudin vitae', 'Aenean lectus. Pellentesque eget nunc.', 'http://dummyimage.com/250x231.png/5fa2dd/ffffff', 9, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('tellus in sagittis dui vel nisl duis ac nibh', 'Pellentesque eget nunc.', 'http://dummyimage.com/118x125.png/ff4444/ffffff', 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('ut rhoncus aliquet', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', null, 3, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('hac habitasse platea dictumst aliquam augue quam sollicitudin', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'http://dummyimage.com/192x194.png/5fa2dd/ffffff', 1, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('sit amet erat nulla tempus vivamus in felis', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://dummyimage.com/119x152.png/5fa2dd/ffffff', 4, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('tortor id nulla ultrices aliquet maecenas leo odio condimentum', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'http://dummyimage.com/248x118.png/dddddd/000000', 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec vitae nisi nam ultrices libero non mattis pulvinar', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'http://dummyimage.com/224x201.png/cc0000/ffffff', 10, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('risus dapibus augue vel accumsan tellus nisi eu orci mauris', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/219x129.png/ff4444/ffffff', 7, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('dictumst morbi vestibulum velit id', 'Cras pellentesque volutpat dui.', 'http://dummyimage.com/150x136.png/dddddd/000000', 3, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('sit amet nulla quisque', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'http://dummyimage.com/166x176.png/5fa2dd/ffffff', 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('in est risus auctor sed tristique in tempus', 'Nullam varius. Nulla facilisi.', 'http://dummyimage.com/186x184.png/cc0000/ffffff', 2, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('proin interdum mauris non ligula', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', null, 8, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('primis in faucibus orci', 'In quis justo. Maecenas rhoncus aliquam lacus.', null, 5, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('lorem ipsum dolor sit amet', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'http://dummyimage.com/174x228.png/5fa2dd/ffffff', 7, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('tellus semper interdum', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'http://dummyimage.com/130x191.png/cc0000/ffffff', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('morbi non quam nec dui', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', null, 5, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('a pede posuere nonummy integer non', 'Proin eu mi.', 'http://dummyimage.com/144x234.png/cc0000/ffffff', 1, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('ut rhoncus aliquet pulvinar sed nisl nunc', 'Praesent blandit.', 'http://dummyimage.com/245x161.png/cc0000/ffffff', 6, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec odio justo sollicitudin ut suscipit', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', null, 9, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('habitasse platea dictumst maecenas ut massa quis augue', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 'http://dummyimage.com/160x227.png/ff4444/ffffff', 3, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('at nibh in hac habitasse platea dictumst aliquam augue quam', 'Sed vel enim sit amet nunc viverra dapibus.', 'http://dummyimage.com/215x126.png/dddddd/000000', 4, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('suspendisse ornare consequat lectus in est', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://dummyimage.com/191x131.png/dddddd/000000', 6, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec ut mauris eget massa tempor', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'http://dummyimage.com/170x209.png/ff4444/ffffff', 2, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('mauris eget massa tempor convallis', 'Nunc purus. Phasellus in felis. Donec semper sapien a libero.', 'http://dummyimage.com/219x221.png/cc0000/ffffff', 7, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('nec condimentum neque sapien placerat ante nulla', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'http://dummyimage.com/196x122.png/ff4444/ffffff', 3, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('nec dui luctus rutrum nulla tellus in sagittis', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 'http://dummyimage.com/149x202.png/cc0000/ffffff', 10, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('in blandit ultrices enim lorem ipsum dolor sit', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'http://dummyimage.com/221x174.png/5fa2dd/ffffff', 1, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('sodales scelerisque mauris sit amet eros suspendisse', 'Morbi non quam nec dui luctus rutrum.', 'http://dummyimage.com/221x154.png/ff4444/ffffff', 2, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('eleifend quam a odio in hac habitasse platea dictumst', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'http://dummyimage.com/185x238.png/cc0000/ffffff', 4, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec ut mauris eget', 'Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/154x160.png/dddddd/000000', 7, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('purus phasellus in felis donec semper sapien', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', null, 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('porttitor lacus at', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/211x249.png/dddddd/000000', 10, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('vestibulum velit id pretium iaculis diam erat fermentum justo', 'Vivamus tortor.', 'http://dummyimage.com/205x207.png/cc0000/ffffff', 4, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('fusce consequat nulla nisl nunc nisl duis bibendum felis', 'Donec quis orci eget orci vehicula condimentum.', 'http://dummyimage.com/133x101.png/dddddd/000000', 1, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('porttitor pede justo eu massa', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'http://dummyimage.com/189x222.png/5fa2dd/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('pretium nisl ut', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 'http://dummyimage.com/107x123.png/dddddd/000000', 5, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec posuere metus vitae ipsum aliquam non', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 'http://dummyimage.com/140x183.png/ff4444/ffffff', 8, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('nec dui luctus rutrum nulla tellus', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'http://dummyimage.com/132x181.png/cc0000/ffffff', 9, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('id massa id nisl venenatis lacinia', 'Sed ante. Vivamus tortor.', null, 3, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('rhoncus aliquet pulvinar', 'Phasellus sit amet erat. Nulla tempus.', 'http://dummyimage.com/221x168.png/cc0000/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('ut rhoncus aliquet pulvinar sed nisl nunc', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://dummyimage.com/145x226.png/5fa2dd/ffffff', 3, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('condimentum curabitur in libero ut massa volutpat convallis morbi', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'http://dummyimage.com/161x110.png/cc0000/ffffff', 5, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('sagittis sapien cum sociis', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'http://dummyimage.com/217x146.png/cc0000/ffffff', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('in est risus auctor sed tristique in', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'http://dummyimage.com/105x131.png/ff4444/ffffff', 3, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('id nulla ultrices aliquet', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'http://dummyimage.com/137x149.png/cc0000/ffffff', 4, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('donec posuere metus vitae', 'Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://dummyimage.com/206x165.png/cc0000/ffffff', 3, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('in imperdiet et commodo vulputate justo in blandit ultrices enim', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 'http://dummyimage.com/229x223.png/dddddd/000000', 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 'http://dummyimage.com/154x142.png/ff4444/ffffff', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('in est risus', 'Proin eu mi. Nulla ac enim.', null, 9, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('feugiat et eros vestibulum ac est lacinia nisi venenatis tristique', 'Maecenas tincidunt lacus at velit.', null, 5, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('mi nulla ac enim in tempor turpis nec', 'Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/163x221.png/dddddd/000000', 4, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('metus aenean fermentum', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/136x104.png/dddddd/000000', 10, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'http://dummyimage.com/116x192.png/dddddd/000000', 2, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('ullamcorper augue a suscipit nulla elit ac', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', null, 10, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/215x227.png/cc0000/ffffff', 3, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('nunc rhoncus dui vel sem sed sagittis', 'Vivamus tortor. Duis mattis egestas metus.', 'http://dummyimage.com/246x208.png/dddddd/000000', 7, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('eget massa tempor convallis nulla', 'Nulla tellus.', 'http://dummyimage.com/124x181.png/ff4444/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('sapien a libero', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio.', 'http://dummyimage.com/148x117.png/cc0000/ffffff', 7, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('augue quam sollicitudin vitae consectetuer eget', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'http://dummyimage.com/209x140.png/ff4444/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 'Integer non velit.', 'http://dummyimage.com/113x212.png/cc0000/ffffff', 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('ultrices libero non mattis pulvinar', 'Nulla ac enim.', null, 2, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('pede justo eu', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', null, 8, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('nunc vestibulum ante ipsum primis in faucibus orci luctus et', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', null, 5, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('massa volutpat convallis morbi odio', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://dummyimage.com/116x229.png/cc0000/ffffff', 7, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('at feugiat non pretium quis', 'Nulla facilisi.', 'http://dummyimage.com/138x199.png/5fa2dd/ffffff', 9, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('ac tellus semper interdum mauris ullamcorper', 'Aliquam sit amet diam in magna bibendum imperdiet.', 'http://dummyimage.com/213x124.png/dddddd/000000', 3, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('convallis duis consequat dui', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 'http://dummyimage.com/237x210.png/ff4444/ffffff', 2, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('odio elementum eu interdum eu tincidunt', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://dummyimage.com/131x249.png/dddddd/000000', 6, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('pellentesque ultrices mattis odio donec', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 'http://dummyimage.com/248x205.png/cc0000/ffffff', 4, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('est et tempus semper est', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'http://dummyimage.com/214x124.png/dddddd/000000', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('morbi odio odio elementum eu interdum eu tincidunt in leo', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'http://dummyimage.com/173x222.png/dddddd/000000', 4, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('mauris ullamcorper purus sit amet nulla quisque', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', null, 2, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('dapibus augue vel accumsan tellus nisi eu orci mauris', 'Nulla tellus. In sagittis dui vel nisl.', null, 1, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('lobortis sapien sapien non', 'Aenean sit amet justo. Morbi ut odio.', 'http://dummyimage.com/127x177.png/cc0000/ffffff', 5, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('turpis integer aliquet massa id lobortis convallis', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.', 'http://dummyimage.com/250x163.png/5fa2dd/ffffff', 3, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('platea dictumst etiam faucibus cursus urna ut tellus', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'http://dummyimage.com/164x196.png/ff4444/ffffff', 6, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('ante ipsum primis in faucibus orci luctus et', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'http://dummyimage.com/160x106.png/dddddd/000000', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('sapien a libero nam dui', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', null, 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('placerat ante nulla justo aliquam quis turpis eget elit', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'http://dummyimage.com/241x116.png/dddddd/000000', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('dui vel sem sed sagittis', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'http://dummyimage.com/183x136.png/ff4444/ffffff', 7, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('ipsum primis in faucibus orci luctus et ultrices', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.', 'http://dummyimage.com/151x223.png/5fa2dd/ffffff', 2, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/159x151.png/cc0000/ffffff', 5, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('duis at velit eu est congue elementum in', 'Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'http://dummyimage.com/242x240.png/5fa2dd/ffffff', 10, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('in quis justo maecenas rhoncus aliquam lacus', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'http://dummyimage.com/242x137.png/cc0000/ffffff', 3, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('nulla quisque arcu libero rutrum', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'http://dummyimage.com/168x100.png/ff4444/ffffff', 10, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('tristique in tempus', 'Proin interdum mauris non ligula pellentesque ultrices.', 'http://dummyimage.com/146x103.png/dddddd/000000', 2, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('turpis sed ante vivamus', 'Proin risus.', null, 6, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('sagittis sapien cum sociis natoque penatibus et magnis dis parturient', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', null, 9, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('eros suspendisse accumsan tortor quis', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'http://dummyimage.com/121x195.png/5fa2dd/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('neque vestibulum eget vulputate', 'Ut at dolor quis odio consequat varius.', 'http://dummyimage.com/137x137.png/ff4444/ffffff', 2, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('eu est congue elementum in hac habitasse platea dictumst morbi', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'http://dummyimage.com/140x195.png/5fa2dd/ffffff', 6, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('luctus et ultrices posuere cubilia', 'Maecenas tincidunt lacus at velit.', 'http://dummyimage.com/155x107.png/ff4444/ffffff', 6, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('auctor sed tristique in tempus sit amet sem', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', null, 4, 1);
insert into recipes (title, description, image, author_id, visibility_id) values ('rutrum at lorem integer', 'Aenean lectus. Pellentesque eget nunc.', null, 9, 2);
insert into recipes (title, description, image, author_id, visibility_id) values ('nisi vulputate nonummy', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', null, 10, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('phasellus sit amet erat nulla tempus vivamus in', 'Duis consequat dui nec nisi volutpat eleifend.', 'http://dummyimage.com/142x214.png/cc0000/ffffff', 8, 3);
insert into recipes (title, description, image, author_id, visibility_id) values ('varius integer ac leo pellentesque ultrices mattis odio donec', 'Proin risus.', 'http://dummyimage.com/202x249.png/cc0000/ffffff', 2, 3);

-- Insert tags
insert into tags (value) values ('dapibus duis');
insert into tags (value) values ('vitae');
insert into tags (value) values ('sociis natoque penatibus');
insert into tags (value) values ('in');
insert into tags (value) values ('nec molestie sed');
insert into tags (value) values ('etiam pretium iaculis');
insert into tags (value) values ('tincidunt eu');
insert into tags (value) values ('sed tincidunt eu');
insert into tags (value) values ('aliquam convallis nunc');
insert into tags (value) values ('potenti in eleifend');

-- Insert recipe tags
insert into recipe_tags (recipe_id, tag_id) values (20, 2);
insert into recipe_tags (recipe_id, tag_id) values (33, 6);
insert into recipe_tags (recipe_id, tag_id) values (28, 6);
insert into recipe_tags (recipe_id, tag_id) values (5, 7);
insert into recipe_tags (recipe_id, tag_id) values (99, 3);
insert into recipe_tags (recipe_id, tag_id) values (24, 5);
insert into recipe_tags (recipe_id, tag_id) values (86, 3);
insert into recipe_tags (recipe_id, tag_id) values (10, 3);
insert into recipe_tags (recipe_id, tag_id) values (6, 5);
insert into recipe_tags (recipe_id, tag_id) values (3, 8);

-- Insert shelves
insert into shelves (user_id, label) values (1, 'donec vitae nisi');
insert into shelves (user_id, label) values (7, 'aenean auctor gravida sem');
insert into shelves (user_id, label) values (5, 'congue elementum in');
insert into shelves (user_id, label) values (5, 'aliquam non');
insert into shelves (user_id, label) values (2, 'aliquet maecenas leo odio');
insert into shelves (user_id, label) values (5, 'varius nulla facilisi');
insert into shelves (user_id, label) values (3, 'lacus curabitur');
insert into shelves (user_id, label) values (3, 'amet justo morbi');
insert into shelves (user_id, label) values (4, 'ante ipsum primis in faucibus');
insert into shelves (user_id, label) values (10, 'vitae consectetuer');

-- Insert shelf recipes
insert into shelf_recipes (shelf_id, recipe_id) values (10, 42);
insert into shelf_recipes (shelf_id, recipe_id) values (10, 17);
insert into shelf_recipes (shelf_id, recipe_id) values (7, 19);
insert into shelf_recipes (shelf_id, recipe_id) values (8, 48);
insert into shelf_recipes (shelf_id, recipe_id) values (4, 95);
insert into shelf_recipes (shelf_id, recipe_id) values (7, 99);
insert into shelf_recipes (shelf_id, recipe_id) values (10, 36);
insert into shelf_recipes (shelf_id, recipe_id) values (9, 27);
insert into shelf_recipes (shelf_id, recipe_id) values (9, 96);
insert into shelf_recipes (shelf_id, recipe_id) values (3, 55);

-- insert profiles
insert into profiles (user_id, bio) values (1, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into profiles (user_id, bio) values (2, 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into profiles (user_id, bio) values (3, 'Vestibulum rutrum rutrum neque.');
insert into profiles (user_id, bio) values (4, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into profiles (user_id, bio) values (5, 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into profiles (user_id, bio) values (6, 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into profiles (user_id, bio) values (7, 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into profiles (user_id, bio) values (8, 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into profiles (user_id, bio) values (9, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into profiles (user_id, bio) values (10, 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');

-- insert communities
insert into communities (name, description, admin_id) values ('sem praesent id massa', 'sagittis nam congue risus semper porta volutpat quam pede', 5);
insert into communities (name, description, admin_id) values ('id luctus nec molestie', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', 1);
insert into communities (name, description, admin_id) values ('lectus in quam', 'in hac habitasse platea dictumst maecenas', 7);
insert into communities (name, description, admin_id) values ('ut dolor morbi vel lectus', 'mus vivamus vestibulum sagittis sapien cum sociis', 8);
insert into communities (name, description, admin_id) values ('vestibulum rutrum rutrum neque', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est', 3);
